// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnlxomvycytegwgptucv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ubHhvbXZ5Y3l0ZWd3Z3B0dWN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NTE5MDcsImV4cCI6MjA1NzQyNzkwN30.ZT5ky_1rU0a8fg39iz7DRhq3yVZo6UB8NuPf0ywMLdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);